live_config_reload = true

# import = [ "~/.config/alacritty/themes/gruvbox_material.toml" ]
import = [ "~/.config/alacritty/themes/everforest.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[env]
# TERM = "xterm-256color"
TERM = "alacritty-direct"
# TERM = "tmux-256color"

[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font"
# style = "Regular"
style = "ExtraLight"

[window]
decorations = "none"
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"
